main:
  method: 'get'
  path: ~
  controller: App\Controller\HomeController
  action: index

test:
  method: 'get'
  path: test
  controller: App\Controller\HomeController
  action: test

trailer:
  method: 'get'
  path: trailer/{id}
  controller: App\Controller\HomeController
  action: trailer
  requirements:
    page: '\d+'
